"""Initial schema

Revision ID: 5ab083d947af
Revises:
Create Date: 2026-03-06 18:34:57.772422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab083d947af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chambers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chambers_id'), 'chambers', ['id'], unique=False)
    op.create_index(op.f('ix_chambers_name'), 'chambers', ['name'], unique=True)
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_config_id'), 'system_config', ['id'], unique=False)
    op.create_index(op.f('ix_system_config_key'), 'system_config', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('actuator_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamber_id', sa.Integer(), nullable=True),
    sa.Column('actuator_type', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chamber_id'], ['chambers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actuator_logs_actuator_type'), 'actuator_logs', ['actuator_type'], unique=False)
    op.create_index(op.f('ix_actuator_logs_chamber_id'), 'actuator_logs', ['chamber_id'], unique=False)
    op.create_index(op.f('ix_actuator_logs_id'), 'actuator_logs', ['id'], unique=False)
    op.create_index(op.f('ix_actuator_logs_timestamp'), 'actuator_logs', ['timestamp'], unique=False)
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamber_id', sa.Integer(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('planted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chamber_id'], ['chambers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plants_id'), 'plants', ['id'], unique=False)
    op.create_index(op.f('ix_plants_species'), 'plants', ['species'], unique=False)
    op.create_table('harvest_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvest_queue_id'), 'harvest_queue', ['id'], unique=False)
    op.create_index(op.f('ix_harvest_queue_plant_id'), 'harvest_queue', ['plant_id'], unique=False)
    op.create_index(op.f('ix_harvest_queue_scheduled_time'), 'harvest_queue', ['scheduled_time'], unique=False)
    op.create_index(op.f('ix_harvest_queue_status'), 'harvest_queue', ['status'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('prediction_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_id'), 'ml_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_plant_id'), 'ml_predictions', ['plant_id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_prediction_type'), 'ml_predictions', ['prediction_type'], unique=False)
    op.create_index(op.f('ix_ml_predictions_timestamp'), 'ml_predictions', ['timestamp'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('sensor_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_id'), 'sensor_readings', ['id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_plant_id'), 'sensor_readings', ['plant_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_sensor_type'), 'sensor_readings', ['sensor_type'], unique=False)
    op.create_index(op.f('ix_sensor_readings_timestamp'), 'sensor_readings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_timestamp'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_sensor_type'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_plant_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_ml_predictions_timestamp'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_prediction_type'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_plant_id'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_id'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_harvest_queue_status'), table_name='harvest_queue')
    op.drop_index(op.f('ix_harvest_queue_scheduled_time'), table_name='harvest_queue')
    op.drop_index(op.f('ix_harvest_queue_plant_id'), table_name='harvest_queue')
    op.drop_index(op.f('ix_harvest_queue_id'), table_name='harvest_queue')
    op.drop_table('harvest_queue')
    op.drop_index(op.f('ix_plants_species'), table_name='plants')
    op.drop_index(op.f('ix_plants_id'), table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_actuator_logs_timestamp'), table_name='actuator_logs')
    op.drop_index(op.f('ix_actuator_logs_id'), table_name='actuator_logs')
    op.drop_index(op.f('ix_actuator_logs_chamber_id'), table_name='actuator_logs')
    op.drop_index(op.f('ix_actuator_logs_actuator_type'), table_name='actuator_logs')
    op.drop_table('actuator_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_config_key'), table_name='system_config')
    op.drop_index(op.f('ix_system_config_id'), table_name='system_config')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_chambers_name'), table_name='chambers')
    op.drop_index(op.f('ix_chambers_id'), table_name='chambers')
    op.drop_table('chambers')
    # ### end Alembic commands ###
